# Generated by Django 5.2.8 on 2025-12-22 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_remove_employee_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sick_leave', models.FloatField(default=0)),
                ('casual_leave', models.FloatField(default=0)),
                ('optional_leave', models.FloatField(default=0)),
                ('earned_leave', models.FloatField(default=0)),
                ('total_sick_leave', models.FloatField(default=0)),
                ('total_casual_leave', models.FloatField(default=0)),
                ('total_optional_leave', models.FloatField(default=0)),
                ('total_earned_leave', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='user.employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_updated_by', to='user.user')),
            ],
            options={
                'db_table': 'leave_balances',
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('leave_type', models.CharField(max_length=20)),
                ('apply_date', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_days', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('leave_without_pay', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('reason', models.TextField(blank=True, null=True)),
                ('attachment', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('half_day_start_type', models.CharField(blank=True, max_length=20, null=True)),
                ('half_day_end_type', models.CharField(blank=True, max_length=10, null=True)),
                ('approve_date', models.DateField(blank=True, null=True)),
                ('approve_comment', models.TextField(blank=True, null=True)),
                ('reject_date', models.DateField(blank=True, null=True)),
                ('reject_comment', models.TextField(blank=True, null=True)),
                ('casual_deducted', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('earned_deducted', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('sick_deducted', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('optional_deducted', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_actions', to='user.user')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='user.employee')),
            ],
            options={
                'db_table': 'leave_requests',
            },
        ),
    ]
