# Generated by Django 5.2.8 on 2025-12-18 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='image',
        ),
    ]
